import { ClinicalSummaryResponse } from "@/lib/openai/smart-parser";

interface Props {
  content: string;
}

export function SafeClinicalSummaryRender({ content }: Props) {
  let parsed: ClinicalSummaryResponse | null = null;
  
  try {
    parsed = JSON.parse(content);
  } catch (e) {
    // Fallback if content isn't valid JSON (e.g. legacy text)
    return <div className="whitespace-pre-wrap">{content}</div>;
  }

  if (!parsed) {
    return <div className="whitespace-pre-wrap">{content}</div>;
  }

  return (
    <div className="space-y-4 text-sm">
      <div className="border-b border-calm-border pb-2 mb-3">
        <h3 className="text-calm-blue font-semibold uppercase tracking-wide text-xs">
          Clinical Visit Summary
        </h3>
      </div>
      
      <div className="space-y-3">
        <section>
          <h4 className="font-semibold text-calm-text-strong mb-1">Chief Complaint</h4>
          <p className="text-calm-text bg-calm-surface rounded-md p-2 border border-calm-border/50">
            {parsed.chief_complaint}
          </p>
        </section>

        <section>
          <h4 className="font-semibold text-calm-text-strong mb-1">Medication Review</h4>
          <p className="text-calm-text bg-calm-surface rounded-md p-2 border border-calm-border/50">
            {parsed.medication_review}
          </p>
        </section>

        <section>
          <h4 className="font-semibold text-calm-text-strong mb-1">Patient Goals</h4>
          <p className="text-calm-text bg-calm-surface rounded-md p-2 border border-calm-border/50">
            {parsed.patient_goal}
          </p>
        </section>
      </div>

      <div className="pt-2 text-xs text-calm-text-muted italic">
        Generated by AI Assistant &bull; Review carefully before sharing
      </div>
    </div>
  );
}
